/*
 * This source file was generated by the Gradle 'init' task
 */
package com.delbertina;

import org.junit.Test;

import static org.junit.Assert.*;

// A test that doesn't really test anything
// Just to make sure that tests are working
public class delarioTest {
    @Test public void appHasAGreeting() {
        delario classUnderTest = new delario();
        assertFalse("app should not be in Christmas mode", classUnderTest.isChristmas);
    }
}
